import { userProfile } from "@/types/user/user"

export type djItem = {
    dj: userProfile,
    category: string,
    secondCategory: string,
    buyed: boolean,
    price: number,
    originalPrice: number,
    discountPrice: null,
    purchaseCount: number,
    lastProgramName: string,
    videos: null,
    finished: boolean,
    underShelf: boolean,
    liveInfo: null,
    playCount: number,
    privacy: boolean,
    icon: null,
    manualTagsDTO: null,
    descPicList: any[],
    replaceRadioId: number,
    replaceRadio: null,
    shortName: null,
    categoryId: number,
    taskId: number,
    picId: number,
    programCount: number,
    subCount: number,
    participateUidList: any[],
    operateUidList: any[],
    picUrl: string,
    lastProgramId: number,
    feeScope: number,
    lastProgramCreateTime: number,
    radioFeeType: number,
    intervenePicUrl: string,
    intervenePicId: number,
    dynamic: boolean,
    desc: string,
    createTime: number,
    name: string,
    id: number,
    rcmdtext: null
}